
<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class History_model extends CI_Model {

    public $table = 'historyprogress';
    public $id = 'idhistory';
    public $order = 'DESC';

    function __construct() {
        parent::__construct();
    }

    public function index() {
        $history = $this->History_model->get_all();

        $data = array(
            'history_data' => $history
        );

        $this->template->display('history/history', $data);
    }
    // get all
     function get_all() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get_where($this->table,array('status' => 1))->result();
    }

    function get_rows() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get_where($this->table, array('idusers' => $this->session->userdata('idusers')))->num_rows();
    }

    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idservis', $q);
        $this->db->or_like('tglkeluar ', $q);
        $this->db->or_like('tglmasuk', $q);
        $this->db->or_like('kilometer ', $q);
        $this->db->or_like('platnomor ', $q);
        $this->db->or_like('idcustomer ', $q);
        $this->db->or_like('idpekerjaan', $q);
        $this->db->or_like('idusers', $q);
        $this->db->or_like('idmodel', $q);
        $this->db->or_like('idproduk', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idservis', $q);
        $this->db->or_like('tglkeluar ', $q);
        $this->db->or_like('tglmasuk', $q);
        $this->db->or_like('kilometer ', $q);
        $this->db->or_like('platnomor ', $q);
        $this->db->or_like('idcustomer ', $q);
        $this->db->or_like('idpekerjaan', $q);
        $this->db->or_like('idusers', $q);
        $this->db->or_like('idmodel', $q);
        $this->db->or_like('idproduk', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

        // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);

    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }


}

/* End of file Kendaraan_model.php */
/* Location: ./application/models/Kendaraan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:09:25 */
/* http://harviacode.com */
