
<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jabatanuser_model extends CI_Model {

    public $table = 'jabatanuser';
    public $id = 'nik';
    public $order = 'DESC';

    function __construct() {
        parent::__construct();
    }
    /*
    public function index() {
        $karyawan = $this->Karyawan_model->get_all();

        $data = array(
            'karyawan_data' => $karyawan
        );

        $this->template->display('karyawan_data/tb_karyawan_list', $data);
    }*/
    // get all
     function get_all() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_rows() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get_where($this->table, array('idusers' =>$this->session->userdata('idusers')))->num_rows();
    }

    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

   
     // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }   

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }


}

/* End of file Karyawan_model.php */
/* Location: ./application/models/Karyawan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:09:25 */
/* http://harviacode.com */
