
<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pelanggan_model extends CI_Model {

    public $table = 'customer';
    public $id = 'idcustomer';
    public $order = 'DESC';

    function __construct() {
        parent::__construct();
    }

    // get all
     function get_all() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_rows() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get_where($this->table, array('idusers' => $this->session->userdata('idusers')))->num_rows();
    }

    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_nama($nama){
        $this->db->select('*')
                ->from('customer')
                ->where('namacustomer',$nama);
        return $this->db->get()->row_array();
    }

    function get_by_nama_pkb($nama,$pkb){
        $this->db->select('*')
                ->from('customer')
                ->where('namacustomer',$nama)
                ->where('norangka',$pkb);
        return $this->db->get()->row_array();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idcustomer', $q);
        $this->db->or_like('namacustomer', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('telphp', $q);
       // $this->db->or_like('telpkantor', $q);
       // $this->db->or_like('telprumah', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idcustomer', $q);
        $this->db->or_like('namacustomer', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('telphp', $q);
       // $this->db->or_like('telpkantor', $q);
       // $this->db->or_like('telprumah', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pelanggan_model.php */
/* Location: ./application/models/Pelanggan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:09:25 */
/* http://harviacode.com */